services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
    ports:
      - "8888:8888"  # For Jupyter notebooks
    command: /opt/venv/bin/jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' 